### ISSUE TITLE
Container instance not working properly

### ISSUE THREAD

**Issue by dtarek1** [MicrosoftLearning/AI-102-AIEngineer#190] opened 2023-05-16 11:41 UTC
# Module: 04
#### Step: 03
Use a Cognitive Services Container

Description of issue
container instance not working when running rest-test. gives "empty container" error
Repro steps:

1.
1.
1.

**Comment by ivorb** [comment] 2023-05-19 18:31
dupe of #187 - still investigating if there is a workaround to do for this lab

**Closed by ivorb** 2023-05-19 18:31 UTC
