### ISSUE TITLE
New search for London hotel is getting error in the web app 

### ISSUE THREAD

**Issue by Prasanna-Spektra** [MicrosoftLearning/AI-102-AIEngineer#96] opened 2021-11-22 17:32 UTC
# Module: 12
#### Step: 03 to 09

Description of issue
After launching Web app, while searching for **London hotel** it showing as "**_Opps! An error occurred '>=' not supported between instances of 'NoneType' and 'float'._**"
But new search for **quiet hotel in New York** is showing results page with 0 results

Repro steps:

1. Tried multiple time with all the possible keywords but for **quiet hotel in New York** is showing results page 
1.
1.

![image](https://user-images.githubusercontent.com/85864326/142906223-790d7e27-6add-418f-9146-fd010ab00e1f.png)

![image](https://user-images.githubusercontent.com/85864326/142906364-6ce689fc-ffb7-4bd1-a929-988ef0475717.png)

![image](https://user-images.githubusercontent.com/85864326/142906676-d8921c46-a684-4e36-b492-e9aa56bd1247.png)

**Comment by drguthals** [comment] 2021-11-23 16:17
Thanks @Prasanna-Spektra I will look through this now!

**Comment by drguthals** [comment] 2021-11-23 19:04
@Prasanna-Spektra - I wanted to confirm something, did you receive any errors while you were running this in the earlier steps (e.g. on [this step](https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/Instructions/22-azure-search.md#query-the-modified-index))?

**Comment by Prasanna-Spektra** [comment] 2021-11-25 08:11
@drguthals we got one issue but we resolved before this step.
1. One issue is with Flask module (No Module named Flask) issue and it got resolved after updating the PIP version.

**Comment by C-Youssef** [comment] 2021-12-03 00:48
I had the same issue trying multiple search queries such as 'New York' or 'London hotel' using the Flask web app. 

Search queries with terms that do not exist in the indexed documents do not result in an error. They simply show no search results, as expected.  

The error above resulted from comparing a variable that has null instances with a float. Time for some debugging ...

**Comment by C-Youssef** [comment] 2021-12-03 03:35
This issue is caused by comparing null instances of the sentiment score and the float 0.5. See lab file 22-Create-a-search-solution/Python/margies-travel/templates/search.html.

I just submitted a simple fix in pull request #102. 

All search queries should run fine after this update.

**Comment by C-Youssef** [comment] 2021-12-03 15:40
@Prasanna-Spektra - Could you query your modifed index, after adding sentiment and URL fields, with the following query:

search=*&$count=true&$select=metadata_storage_name,sentiment&$filter=sentiment eq null

You should get "@odata.count": 0. If not, review your index or redo it from scratch.  You may have some indexed documents with no sentiment scores, causing the failure of the search queries when using the web app.

**Comment by GraemeMalcolm** [comment] 2021-12-07 14:57
Closed as non-repro

**Closed by GraemeMalcolm** 2021-12-07 14:57 UTC
